# Generated by Django 2.2.5 on 2019-09-30 17:41

from django.db import migrations, models
import page.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', page.core.models.StreamField()),
            ],
        ),
    ]
