# Generated by Django 2.2.5 on 2019-09-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
