# Generated by Django 2.1.12 on 2019-09-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_socialmediainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='users.Profile', verbose_name='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SkillObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Skill Name')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillObject', to='users.Skill', verbose_name='Skill Object')),
            ],
        ),
    ]
