# Generated by Django 2.1.12 on 2019-09-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_skillobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skillobject',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillObject',
        ),
    ]
