# Generated by Django 2.1.12 on 2019-09-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150, verbose_name='Degree')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('session', models.CharField(max_length=50, verbose_name='Session')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.Profile', verbose_name='Profile')),
            ],
        ),
    ]
