# Generated by Django 2.2.5 on 2019-10-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0008_auto_20190912_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.SmallIntegerField(choices=[(1, 'Administrator'), (2, 'Moderator'), (3, 'Editor'), (4, 'Subscriber')], default=1, verbose_name='User Role')),
                ('permissions', models.ManyToManyField(related_name='user_role', to='auth.Permission', verbose_name='Permissions')),
            ],
        ),
    ]
