# Generated by Django 2.2.5 on 2019-10-03 10:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191003_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_photo_upload_path, verbose_name='Avatar'),
        ),
    ]
