# Generated by Django 2.1.12 on 2019-09-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Menu Text')),
                ('url', models.CharField(max_length=255, verbose_name='Menu URL')),
                ('allow_submenu', models.BooleanField(choices=[('Yes', True), ('No', False)], default=False)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='cms_admin.MenuItem')),
            ],
        ),
    ]
