# Generated by Django 2.1.12 on 2019-09-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0003_auto_20190923_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
