# Generated by Django 2.2.5 on 2019-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_admin', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
