# Generated by Django 2.1.12 on 2019-09-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190912_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='react',
            name='ip_address',
        ),
    ]
