# Generated by Django 2.2.5 on 2019-09-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import media_browser.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('image', models.ImageField(height_field='heigh', max_length=500, upload_to=media_browser.models.image_upload_path, verbose_name='Image', width_field='width')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
