# Generated by Django 2.2.5 on 2019-09-26 17:44

from django.db import migrations, models
import media_browser.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='description',
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='image',
            field=models.ImageField(height_field='height', max_length=500, upload_to=media_browser.models.image_upload_path, verbose_name='Image', width_field='width'),
        ),
    ]
