# Generated by Django 2.1.12 on 2019-09-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Menu Text')),
                ('url', models.CharField(max_length=255, verbose_name='Menu URL')),
                ('allow_submenu', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submenus', to='sites.MenuItem')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='sites.SiteInformation', verbose_name='Site')),
            ],
        ),
    ]
