# Generated by Django 2.2.5 on 2019-09-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seen',
            field=models.BooleanField(blank=True, choices=[(True, 'Seen'), (False, 'Not Seen')], default=False, null=True),
        ),
    ]
