# Generated by Django 2.2.5 on 2019-10-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='site',
        ),
    ]
