# Generated by Django 2.2.5 on 2019-10-07 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_browser', '0002_auto_20190926_1744'),
        ('sites', '0009_auto_20191007_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinformation',
            name='site_facicon',
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='site_favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicon', to='media_browser.MediaImage'),
        ),
    ]
